---
# Service: client-x-v1-0-0
apiVersion: v1
kind: Service
metadata:
  name: client-x-v1-0-0
  namespace: demo
spec:
  selector:
    app: client-x
    version: 1.0.0
  ports:
  - protocol: TCP
    port: 9999
    name: dummy-unused-port
